services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.32
    container_name: etcd
    network_mode: host
    entrypoint: /usr/local/bin/etcd
    environment:
      - ETCD_NAME=etcd
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.1.24:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.1.24:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://192.168.1.24:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=dynamo-cluster
    restart: unless-stopped
