version: '3.8'

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    network_mode: host
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.1.24:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.1.24:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://192.168.1.24:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=dynamo-cluster
    restart: unless-stopped
